language: php

dist: trusty

env:
  global:
    - COMPOSER_ROOT_VERSION=2.0.x-dev

matrix:
  include:
    - php: 7.0
      env:
       - DB=MYSQL

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - composer require silverstripe/recipe-cms:1.0.x-dev --no-update
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit simple-styleguide/tests/
