language: php
php:
  - 7.1

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=3.2

before_script:
  - phpenv rehash
  - composer self-update
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit simple-styleguide/tests/
